version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - STRIPE_SIGNING_SECRET=${STRIPE_SIGNING_SECRET}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - MAILCHIMP_CLIENT_ID=${MAILCHIMP_CLIENT_ID}
      - MAILCHIMP_CLIENT_SECRET=${MAILCHIMP_CLIENT_SECRET}
      - MAILCHIMP_REDIRECT_URI=${MAILCHIMP_REDIRECT_URI}
      - MAILCHIMP_STRIPE_REDIRECT_URI=${MAILCHIMP_STRIPE_REDIRECT_URI}