spring.application.name=connect to stripe
environment=DEMO
stripe.signing.secret=absec_Bg2WGu054J2oFBAsmy2aBpKGnTNBTcU3
stripe.endpoint.secret=whsec_df6496634a800a37a23d4320bd4354efc197a67f6d8c0dc575ab1ff4b758f072
stripe.billing.secret=sk_test_51RyoiOF8MQhGKD54PdDAjfrcZgDOM93Q9nrhMe08AxMjwkhg7GAXaQL9LCFGAjMPDMLvnTsnukPzcPBR2XgugRkN00yA6xIXea
stripe.billing.endpoint.secret=whsec_68768defb95720353454d37fa5cd48b7ce2bf97f5997b58cdf11f4414c585cfd
mailchimp.client-id=386657553310
mailchimp.client-secret=d5d92132a64b0bf58e6b4001818294c02c45e42ac1c293c27a
mailchimp.redirect-uri=http://127.0.0.1:8080/api/oauth/mailchimp/callback
mailchimp.stripe.redirect-uri=https://dashboard.stripe.com/dashboard?apps[connecttomailchimp-app][drawer]=
spring.datasource.url=jdbc:postgresql://localhost:5432/connecttostripe
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true

