spring.application.name=connect to stripe
environment=${ENVIRONMENT:DOCKER}
stripe.signing.secret=${STRIPE_SIGNING_SECRET}
stripe.endpoint.secret=${STRIPE_ENDPOINT_SECRET}
mailchimp.client-id=${MAILCHIMP_CLIENT_ID}
mailchimp.client-secret=${MAILCHIMP_CLIENT_SECRET}
mailchimp.redirect-uri=${MAILCHIMP_REDIRECT_URI}
mailchimp.stripe.redirect-uri=${MAILCHIMP_STRIPE_REDIRECT_URI}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
server.port=8080